### PR TITLE
The follow subcommand should be able to read a list of accounts from a YAML file

### PR DESCRIPTION
**Pull request by jlewi**
* This makes it easy to collaboratively maintain lists of accounts to follow
* Right now bluesky supports starter packs but there's no easy way to collaborate on them
* With this PR folks can collaborate using a YAML file in git
* They can then just use the CLI to follow them.
* CLI supports reading directly from a URL so a user can do something like

   ```
   bsky follow -f https://raw.githubusercontent.com/jlewi/bskylists/refs/heads/main/aiengineering.yaml
   ```

### CODE REVIEW

**Comment by jlewi** [comment]
@mattn PTAL.

**Comment by mattn** [comment]
You can do it with xargs and yq?

```
$ cat follows.txt | xargs bsky follow
```

```
$ curl -s https://raw.githubusercontent.com/jlewi/bskylists/refs/heads/main/aiengineering.yaml | yq .accounts[].handle | xargs bsky follow
```

**Comment by jlewi** [comment]
That works but is slightly more inconvenient; if for no other reason than you need yq installed.

**Comment by jlewi** [comment]
Totally understand if you don't want to accept the PR; I can always fork.

**Pull request closed without merging**
